<a href="https://colab.research.google.com/github/arbazcodes8/nlp-/blob/main/NLP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
data=pd.read_csv('/content/twitter4000.csv')

In [ ]:
data.head()

                                              twitts  sentiment
0  is bored and wants to watch a movie  any sugge...          0
1           back in miami.  waiting to unboard ship           0
2  @misskpey awwww dnt dis brng bak memoriessss, ...          0
3                  ughhh i am so tired  blahhhhhhhhh          0
4  @mandagoforth me bad! It's funny though. Zacha...          0

In [ ]:
data['sentiment'].value_counts()

sentiment
0    2000
1    2000
Name: count, dtype: int64

In [ ]:
data['word_count']=data['twitts'].apply(lambda x:len(str(x).split()))